name: daily-hotspot
on:
  schedule:
    - cron: '30 8 * * 1-5'  # UTC 8:30
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: {python-version: '3.11'}
      - run: pip install -r requirements.txt
      - run: python main.py
        env:
          WECOM_KEY: ${{ secrets.WECOM_KEY }}
          TIANYAN_TOKEN: ${{ secrets.TIANYAN_TOKEN }}
